services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  
  grafana:
    ports:
    - 3000:3000
    volumes:
    - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  viweb:


