FROM httpd:2.4

RUN apt update && apt install -y certbot python3-certbot-apache lynx php-zip

#RUN groupadd nc-user
#RUN useradd nc-user -g nc-user
#RUN adduser root nc-user

#RUN certbot certonly -v --agree-tos --webroot \
#    -d thakarn.gizmo-thailand.com \
#    --email tonezzz@hotmail.com \
#    --webroot-path /usr/local/apache2/htdocs

#RUN certbot install --certname thakarn.gizmo-thailand.com
#    --apache \

#    --webroot-path /usr/local/apache2/htdocs
#rm /var/log/letsencrypt/letsencrypt.log
#    --dry-run \
#--apache \
#--apache-vhost-root \
#docker exec -i wp_plugin_viweb_apache apt update && apt install -y certbot python3-certbot-apache lynx
#certbot --apache -d thakarn.gizmo-thailand.com --email tonezzz@hotmail.com -n --agree-tos --webroot-path /usr/local/apache2/htdocs
#docker exec -i wp_plugin_viweb_apache ls /home/nc-user/wp_plugin_viweb/persistent-data/uploads
#certbot --apache -d thakarn.gizmo-thailand.com --email tonezzz@hotmail.com
#docker exec -i wp_plugin_viweb_apache cat /usr/local/apache2/conf/extra/httpd-vhosts.conf
#docker exec -i wp_plugin_viweb_apache certbot --test-cert -d thakarn.gizmo-thailand.com
#docker exec -i wp_plugin_viweb_apache certbot install --certname thakarn.gizmo-thailand.com

#git config --global user.name "Tonezzz"
#git config --global user.email "tonezzz@hotmail.com"

#PHP
#docker exec -i wp_plugin_viweb_apache ls -la /etc/ssl
